DROP SCHEMA IF EXISTS `congtrack`;

CREATE SCHEMA `congtrack`;

DROP TABLE IF EXISTS `congtrack`.`Member` ;

CREATE TABLE IF NOT EXISTS `congtrack`.`Member` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Handle` VARCHAR(15) NOT NULL,
  `LastTweet` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT handle UNIQUE (`Handle`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `congtrack`.`Tally` ;

CREATE TABLE IF NOT EXISTS `congtrack`.`Tally` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Member_ID` INT NOT NULL,
  `Issue_ID` INT NOT NULL,
  `Count` INT UNSIGNED NOT NULL DEFAULT 0,
  `Day` DATE NOT NULL,
  PRIMARY KEY (`ID`, `Member_ID`),
  UNIQUE INDEX `id_UNIQUE` (`ID` ASC),
  INDEX `ISSUE` (`Issue_ID` ASC),
  INDEX `DAY` (`Day` ASC),
  INDEX `MEMBER` (`Member_ID` ASC))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `congtrack`.`Issue` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT name UNIQUE (`Name`))
ENGINE = InnoDB;
